# Generated by Django 4.2.2 on 2023-07-11 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_stock_stockdailydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bookmark_users',
            field=models.ManyToManyField(related_name='bookmark_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
