# Generated by Django 4.2.2 on 2023-07-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_analyze_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='origin_create_at',
            new_name='create_at',
        ),
    ]
