# Generated by Django 4.2.2 on 2023-07-14 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_news_analyze_analyze_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='news',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyze', to='news.news'),
        ),
    ]
