# Generated by Django 4.2.2 on 2023-07-16 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_alter_analyze_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_stock', to=settings.AUTH_USER_MODEL),
        ),
    ]
