# Generated by Django 4.2.2 on 2023-07-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isInfluencer',
            field=models.BooleanField(default=False),
        ),
    ]
