# Generated by Django 4.2.2 on 2023-07-03 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='helpful_users',
            field=models.ManyToManyField(related_name='helpful_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='unhelpful_users',
            field=models.ManyToManyField(related_name='unhelpful_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='unlike_users',
            field=models.ManyToManyField(related_name='unlike_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
