# Generated by Django 4.2.2 on 2023-07-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('boards', '0007_remove_comment_unlike_users_comment_dislike_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.field'),
        ),
    ]
